/**:
  ros__parameters:
    fixed_frame: earth
    near_plane: 0.05
    far_plane: 1000.0
    zoom_factor: 1.0
    render_scale: 0.5
    max_render_fps: 0.0

    input:
      image_topic: /drone0/sensor_measurements/image_raw
      camera_info_topic: /drone0/sensor_measurements/camera_info

    output:
      topic: /drone0/sensor_measurements/image_with_markers
